name: Gradle CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Cache gradle wrapper
      uses: actions/cache@v1
      with:
        path:  ~/.gradle/wrapper
        key:  ${{runner.os}}-gradlewrapper-${{hashFiles('gradle/wrapper/*.*')}}
    - name: Wrapper with Gradle
      run: ./gradlew
